apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ${domain}-cert
  namespace: ${namespace}
spec:
  commonName: ${domain}
  dnsNames:
    - ${domain}
  secretName: ${domain}-cert
  issuerRef:
    kind: ClusterIssuer
    name: ${issuer}
