apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  acme:
    email: ${email_address}
    server: ${server}
    privateKeySecretRef:
      name: ${name}-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
